-- Erstellt und befüllt die Tabelle 'hymnal_nordelbien' mit dem vollständigen
-- Inhaltsverzeichnis des Nordelbischen Gesangbuchs.

-- 1. Tabellenstruktur definieren
-- 'nummer' ist VARCHAR, um Einträge wie '177.1' zu ermöglichen.
CREATE TABLE IF NOT EXISTS hymnal_nordelbien (
    nummer VARCHAR(10) PRIMARY KEY,
    titel TEXT NOT NULL,
    kategorie VARCHAR(255),
    strophenzahl INTEGER NOT NULL
);

-- 2. Bestehende Daten löschen, um einen sauberen Neuimport zu gewährleisten.
DELETE FROM hymnal_nordelbien;

-- 3. Datensätze einfügen
INSERT INTO hymnal_nordelbien (nummer, titel, kategorie, strophenzahl) VALUES
('1', 'Macht hoch die Tür', 'Advent', 5),
('2', 'Er ist die rechte Freudensonn', 'Advent', 3),
('3', 'Gott, heilger Schöpfer aller Stern', 'Advent', 6),
('4', 'Nun komm, der Heiden Heiland', 'Advent', 5),
('5', 'Gottes Sohn ist kommen', 'Advent', 9),
('6', 'Ihr lieben Christen, freut euch nun', 'Advent', 5),
('7', 'O Heiland, reiß die Himmel auf', 'Advent', 7),
('8', 'Es kommt ein Schiff, geladen', 'Advent', 6),
('9', 'Nun jauchzet, all ihr Frommen', 'Advent', 6),
('10', 'Mit Ernst, o Menschenkinder', 'Advent', 4),
('11', 'Wie soll ich dich empfangen', 'Advent', 10),
('12', 'Gott sei Dank durch alle Welt', 'Advent', 4),
('13', 'Tochter Zion, freue dich', 'Advent', 3),
('14', 'Dein König kommt in niedern Hüllen', 'Advent', 6),
('15', '»Tröstet, tröstet«, spricht der Herr', 'Advent', 6),
('16', 'Die Nacht ist vorgedrungen,', 'Advent', 5),
('17', 'Wir sagen euch an den lieben Advent', 'Advent', 4),
('18', 'Seht, die gute Zeit ist nah', 'Advent', 2),
('19', 'O komm, o komm, du Morgenstern', 'Advent', 3),
('20', 'Das Volk, das noch im Finstern wandelt', 'Advent', 8),
('21', 'Seht auf und erhebt eure Häupter', 'Advent', 1),
('22', 'Nun sei uns willkommen, Herre Christ', 'Advent', 1),
('23', 'Gelobet seist du, Jesu Christ', 'Weihnachten', 7),
('24', 'Vom Himmel hoch da komm ich her', 'Weihnachten', 15),
('25', 'Vom Himmel kam der Engel Schar', 'Weihnachten', 6),
('26', 'Ehre sei Gott in der Höhe', 'Weihnachten', 1),
('27', 'Lobt Gott, ihr Christen alle gleich', 'Weihnachten', 6),
('28', 'Also hat Gott die Welt geliebt', 'Weihnachten', 1),
('29', 'Den die Hirten lobeten sehre', 'Weihnachten', 4),
('30', 'Es ist ein Ros entsprungen', 'Weihnachten', 4),
('31', 'Es ist ein Ros entsprungen (Kanon)', 'Weihnachten', 4),
('32', 'Zu Bethlehem geboren', 'Weihnachten', 4),
('33', 'Brich an, du schönes Morgenlicht', 'Weihnachten', 3),
('34', 'Freuet euch, ihr Christen alle', 'Weihnachten', 4),
('35', 'Nun singet und seid froh', 'Weihnachten', 4),
('36', 'Fröhlich soll mein Herze springen', 'Weihnachten', 12),
('37', 'Ich steh an deiner Krippen hier', 'Weihnachten', 9),
('38', 'Wunderbarer Gnadenthron', 'Weihnachten', 3),
('39', 'Kommt und lasst uns Christus ehren', 'Weihnachten', 7),
('40', 'Dies ist die Nacht, da mir erschienen', 'Weihnachten', 5),
('41', 'Jauchzet, ihr Himmel, frohlocket, ihr Engel, in Chören', 'Weihnachten', 7),
('42', 'Dies ist der Tag, den Gott gemacht', 'Weihnachten', 9),
('43', 'Ihr Kinderlein, kommet, o kommet doch all', 'Weihnachten', 6),
('44', 'O du fröhliche, o du selige', 'Weihnachten', 3),
('45', 'Herbei, o ihr Gläub''gen', 'Weihnachten', 4),
('46', 'Stille Nacht, heilige Nacht', 'Weihnachten', 3),
('47', 'Freu dich, Erd und Sternenzelt, Halleluja', 'Weihnachten', 5),
('48', 'Kommet, ihr Hirten, ihr Männer und Fraun', 'Weihnachten', 3),
('49', 'Der Heiland ist geboren', 'Weihnachten', 4),
('50', 'Du Kind, zu dieser heilgen Zeit', 'Weihnachten', 5),
('51', 'Also liebt Gott die arge Welt', 'Weihnachten', 5),
('52', 'Wisst ihr noch, wie es geschehen', 'Weihnachten', 6),
('53', 'Als die Welt verloren', 'Weihnachten', 3),
('54', 'Hört, der Engel helle Lieder', 'Weihnachten', 3),
('55', 'O Bethlehem, du kleine Stadt', 'Weihnachten', 3),
('56', 'Weil Gott in tiefster Nacht erschienen', 'Weihnachten', 5),
('57', 'Uns wird erzählt von Jesus Christ', 'Weihnachten', 5),
('58', 'Nun lasst uns gehn und treten', 'Jahreswende', 15),
('59', 'Das alte Jahr vergangen ist', 'Jahreswende', 6),
('60', 'Freut euch, ihr lieben Christen all', 'Jahreswende', 5),
('61', 'Hilf, Herr Jesu, lass gelingen', 'Jahreswende', 6),
('62', 'Jesus soll die Losung sein', 'Jahreswende', 5),
('63', 'Das Jahr geht still zu Ende', 'Jahreswende', 6),
('64', 'Der du die Zeit in Händen hast', 'Jahreswende', 6),
('65', 'Von guten Mächten treu und still umgeben', 'Jahreswende', 3),
('66', 'Jesus ist kommen, Grund ewiger Freude', 'Epiphanias', 9),
('67', 'Herr Christ, der einig Gotts Sohn', 'Epiphanias', 5),
('68', 'O lieber Herre Jesu Christ', 'Epiphanias', 8),
('69', 'Der Morgenstern ist aufgedrungen', 'Epiphanias', 4),
('70', 'Wie schön leuchtet der Morgenstern', 'Epiphanias', 7),
('71', 'O König aller Ehren', 'Epiphanias', 6),
('72', 'O Jesu Christe, wahres Licht', 'Epiphanias', 6),
('73', 'Auf, Seele, auf und säume nicht', 'Epiphanias', 10),
('74', 'Du Morgenstern, du Licht vom Licht', 'Epiphanias', 4),
('75', 'Ehre sei dir, Christe', 'Passion', 3),
('76', 'O Mensch, bewein dein Sünde groß', 'Passion', 2),
('77', 'Christus, der uns selig macht', 'Passion', 8),
('78', 'Jesu Kreuz, Leiden und Pein', 'Passion', 10),
('79', 'Wir danken dir, Herr Jesu Christ', 'Passion', 4),
('80', 'O Traurigkeit', 'Passion', 5),
('81', 'Herzliebster Jesu, was hast du verbrochen', 'Passion', 11),
('82', 'Wenn meine Sünd'' mich kränken', 'Passion', 11),
('83', 'Ein Lämmlein geht und trägt die Schuld', 'Passion', 7),
('84', 'O Welt, sieh hier dein Leben', 'Passion', 13),
('85', 'O Haupt voll Blut und Wunden', 'Passion', 10),
('86', 'Jesu, meines Lebens Leben', 'Passion', 8),
('87', 'Du großer Schmerzensmann', 'Passion', 6),
('88', 'Jesu, deine Passion', 'Passion', 6),
('89', 'Herr Jesu, deine Angst und Pein', 'Passion', 5),
('90', 'Ich grüße dich am Kreuzesstamm', 'Passion', 2),
('91', 'Herr, stärke mich, dein Leiden zu bedenken', 'Passion', 10),
('92', 'Christe, du Schöpfer aller Welt', 'Passion', 6),
('93', 'Nun gehören unsre Herzen', 'Passion', 4),
('94', 'Das Kreuz ist aufgerichtet', 'Passion', 5),
('95', 'Seht hin, er ist allein im Garten', 'Passion', 4),
('96', 'Du schöner Lebensbaum des Paradieses', 'Passion', 6),
('97', 'Holz auf Jesu Schulter', 'Passion', 6),
('98', 'Korn, das in die Erde, in den Tod versinkt', 'Passion', 3),
('99', 'Christ ist erstanden', 'Ostern', 1),
('100', 'Wir wollen alle fröhlich sein', 'Ostern', 5),
('101', 'Christ lag in Todesbanden', 'Ostern', 7),
('102', 'Jesus Christus, unser Heiland', 'Ostern', 3),
('103', 'Gelobt sei Gott im höchsten Thron', 'Ostern', 6),
('104', 'Singen wir heut mit einem Mund', 'Ostern', 3),
('105', 'Erstanden ist der heilig Christ', 'Ostern', 17),
('106', 'Erschienen ist der herrlich Tag', 'Ostern', 5),
('107', 'Wir danken dir, Herr Jesu Christ', 'Ostern', 3),
('108', 'Mit Freuden zart zu dieser Fahrt', 'Ostern', 3),
('109', 'Heut triumphieret Gottes Sohn', 'Ostern', 6),
('110', 'Die ganze Welt, Herr Jesu Christ', 'Ostern', 6),
('111', 'Frühmorgens, da die Sonn aufgeht', 'Ostern', 15),
('112', 'Auf, auf, mein Herz, mit Freuden', 'Ostern', 8),
('113', 'O Tod, wo ist dein Stachel nun', 'Ostern', 8),
('114', 'Wach auf, mein Herz, die Nacht ist hin', 'Ostern', 10),
('115', 'Jesus lebt, mit ihm auch ich', 'Ostern', 6),
('116', 'Er ist erstanden, Halleluja', 'Ostern', 5),
('117', 'Der schöne Ostertag', 'Ostern', 3),
('118', 'Der Herr ist auferstanden', 'Ostern', 1),
('119', 'Gen Himmel aufgefahren ist', 'Himmelfahrt', 5),
('120', 'Christ fuhr gen Himmel', 'Himmelfahrt', 1),
('121', 'Wir danken dir, Herr Jesu Christ, dass du gen Himmel g''fahren bist', 'Himmelfahrt', 4),
('122', 'Auf Christi Himmelfahrt allein', 'Himmelfahrt', 3),
('123', 'Jesus Christus herrscht als König', 'Himmelfahrt', 11),
('124', 'Nun bitten wir den Heiligen Geist', 'Pfingsten', 4),
('125', 'Komm, Heiliger Geist, Herre Gott', 'Pfingsten', 3),
('126', 'Komm, Gott Schöpfer, Heiliger Geist', 'Pfingsten', 7),
('127', 'Jauchz, Erd, und Himmel, juble hell', 'Pfingsten', 7),
('128', 'Heilger Geist, du Tröster mein', 'Pfingsten', 7),
('129', 'Freut euch, ihr Christen alle', 'Pfingsten', 4),
('130', 'O Heilger Geist, kehr bei uns ein', 'Pfingsten', 7),
('131', 'O Heiliger Geist, o heiliger Gott', 'Pfingsten', 6),
('132', 'Ihr werdet die Kraft des Heiligen Geistes', 'Pfingsten', 1),
('133', 'Zieh ein zu deinen Toren', 'Pfingsten', 13),
('134', 'Komm, o komm, du Geist des Lebens', 'Pfingsten', 8),
('135', 'Schmückt das Fest mit Maien', 'Pfingsten', 7),
('136', 'O komm, du Geist der Wahrheit', 'Pfingsten', 7),
('137', 'Geist des Glaubens, Geist der Stärke', 'Pfingsten', 9),
('138', 'Gott der Vater steh uns bei', 'Trinitatis', 3),
('139', 'Gelobet sei der Herr', 'Trinitatis', 5),
('140', 'Brunn alles Heils, dich ehren wir', 'Trinitatis', 5),
('141', 'Wir wollen singn ein'' Lobgesang', 'Johannestag, 24. Juni', 6),
('142', 'Gott, aller Schöpfung heilger Herr', 'Michaelistag, 29. September', 6),
('143', 'Heut singt die liebe Christenheit', 'Michaelistag, 29. September', 8),
('144', 'Aus tiefer Not lasst uns zu Gott', 'Bußtag', 7),
('145', 'Wach auf, wach auf, du deutsches (unser) Land', 'Bußtag', 7),
('146', 'Nimm von uns, Herr, du treuer Gott', 'Bußtag', 5),
('147', '»Wachet auf«, ruft uns die Stimme', 'Ende des Kirchenjahres', 3),
('148', 'Herzlich tut mich erfreuen', 'Ende des Kirchenjahres', 9),
('149', 'Es ist gewisslich an der Zeit', 'Ende des Kirchenjahres', 7),
('150', 'Jerusalem', 'Ende des Kirchenjahres', 7),
('151', 'Ermuntert euch, ihr Frommen', 'Ende des Kirchenjahres', 8),
('152', 'Wir warten dein, o Gottes Sohn', 'Ende des Kirchenjahres', 4),
('153', 'Der Himmel, der ist', 'Ende des Kirchenjahres', 5),
('154', 'Herr, mach uns stark im Mut, der dich bekennt', 'Ende des Kirchenjahres', 6),
('155', 'Herr Jesu Christ, dich zu uns wend', 'Eingang und Ausgang', 4),
('156', 'Komm, Heiliger Geist', 'Eingang und Ausgang', 1),
('157', 'Lass mich dein sein und bleiben', 'Eingang und Ausgang', 1),
('158', 'O Christe, Morgensterne', 'Eingang und Ausgang', 4),
('159', 'Fröhlich wir nun all fangen an', 'Eingang und Ausgang', 3),
('160', 'Gott Vater, dir sei Dank gesagt und Ehre', 'Eingang und Ausgang', 1),
('161', 'Liebster Jesu, wir sind hier, dich und dein Wort anzuhören', 'Eingang und Ausgang', 3),
('162', 'Gott Lob, der Sonntag kommt herbei', 'Eingang und Ausgang', 4),
('163', 'Unsern Ausgang segne Gott', 'Eingang und Ausgang', 1),
('164', 'Jesu, stärke deine Kinder', 'Eingang und Ausgang', 1),
('165', 'Gott ist gegenwärtig', 'Eingang und Ausgang', 8),
('166', 'Tut mir auf die schöne Pforte', 'Eingang und Ausgang', 6),
('167', 'Wir wollen fröhlich singen', 'Eingang und Ausgang', 4),
('168', 'Du hast uns, Herr, gerufen', 'Eingang und Ausgang', 6),
('169', 'Der Gottesdienst soll fröhlich sein', 'Eingang und Ausgang', 5),
('170', 'Komm, Herr, segne uns, dass wir uns nicht trennen', 'Eingang und Ausgang', 4),
('171', 'Bewahre uns, Gott', 'Eingang und Ausgang', 4),
('172', 'Sende dein Licht und deine Wahrheit', 'Eingang und Ausgang', 1),
('173', 'Der Herr behüte deinen Ausgang und Eingang', 'Eingang und Ausgang', 1),
('174', 'Es segne und behüte uns', 'Eingang und Ausgang', 1),
('175', 'Ausgang und Eingang, Anfang und Ende', 'Eingang und Ausgang', 1),
('176', 'Öffne meine Augen', 'Eingang und Ausgang', 1),
('177.1', 'Ehr sei dem Vater und dem Sohn', 'Ehre sei dem Vater (Gloria Patri)', 1),
('177.2', 'Ehr sei dem Vater und dem Sohn', 'Ehre sei dem Vater (Gloria Patri)', 1),
('177.3', 'Ehre sei dem Vater und dem Sohn', 'Ehre sei dem Vater (Gloria Patri)', 1),
('178.1', 'Kyrie eleison', 'Herr, erbarme dich (Kyrie)', 1),
('178.2', 'Kyrie eleison', 'Herr, erbarme dich (Kyrie)', 1),
('178.3', 'Kyrie eleison', 'Herr, erbarme dich (Kyrie)', 1),
('178.4', 'Kyrie, Gott Vater in Ewigkeit', 'Herr, erbarme dich (Kyrie)', 1),
('178.5', 'Herr, erbarme dich', 'Herr, erbarme dich (Kyrie)', 1),
('178.6', 'Advents-Kyrie', 'Herr, erbarme dich (Kyrie)', 1),
('178.7', 'Oster-Kyrie', 'Herr, erbarme dich (Kyrie)', 1),
('178.8', 'Pfingst-Kyrie', 'Herr, erbarme dich (Kyrie)', 1),
('178.9', 'Kyrie eleison', 'Herr, erbarme dich (Kyrie)', 1),
('178.10', 'Herr, erbarme dich', 'Herr, erbarme dich (Kyrie)', 1),
('178.11', 'Herr, erbarme dich', 'Herr, erbarme dich (Kyrie)', 1),
('178.12', 'Kyrie eleison', 'Herr, erbarme dich (Kyrie)', 1),
('178.13', 'Kyrie eleison', 'Herr, erbarme dich (Kyrie)', 1),
('178.14', 'Kyrie eleison', 'Herr, erbarme dich (Kyrie)', 1),
('179', 'Allein Gott in der Höh sei Ehr', 'Ehre sei Gott in der Höhe (Gloria)', 4),
('180.1', 'Ehre sei Gott in der Höhe', 'Ehre sei Gott in der Höhe (Gloria)', 1),
('180.2', 'Gott in der Höh sei Preis und Ehr', 'Ehre sei Gott in der Höhe (Gloria)', 1),
('180.3', 'Ehre sei Gott in der Höhe', 'Ehre sei Gott in der Höhe (Gloria)', 1),
('180.4', 'Allein Gott in der Höh sei Ehr', 'Ehre sei Gott in der Höhe (Gloria)', 1),
('181.1', 'Halleluja', 'Halleluja', 1),
('181.2', 'Halleluja', 'Halleluja', 1),
('181.3', 'Halleluja', 'Halleluja', 1),
('181.4', 'Halleluja', 'Halleluja', 1),
('181.5', 'Halleluja', 'Halleluja', 1),
('181.6', 'Laudate omnes gentes', 'Halleluja', 1),
('181.7', 'Jubilate Deo', 'Halleluja', 1),
('181.8', 'Halleluja', 'Halleluja', 1),
('182', 'Halleluja - Suchet zuerst...', 'Halleluja', 9),
('183', 'Wir glauben all an einen Gott', 'Glaubensbekenntnis (Credo)', 3),
('184', 'Wir glauben Gott im höchsten Thron', 'Glaubensbekenntnis (Credo)', 5),
('185.1', 'Heilig, heilig, heilig', 'Heilig, heilig, heilig (Sanctus)', 1),
('185.2', 'Heilig, heilig, heilig', 'Heilig, heilig, heilig (Sanctus)', 1),
('185.3', 'Heilig, heilig, heilig', 'Heilig, heilig, heilig (Sanctus)', 1),
('185.4', 'Agios o Theos - Heiliger Herre Gott', 'Heilig, heilig, heilig (Sanctus)', 1),
('185.5', 'Sanctus, sanctus, sanctus', 'Heilig, heilig, heilig (Sanctus)', 1),
('186', 'Vater unser im Himmel', 'Vater unser (Matthäus 6,9-13)', 1),
('187', 'Vater unser im Himmel', 'Vater unser (Matthäus 6,9-13)', 1),
('188', 'Vater unser, Vater im Himmel', 'Vater unser (Matthäus 6,9-13)', 1),
('189', 'Geheimnis des Glaubens', 'Nach den Einsetzungsworten', 1),
('190.1', 'O Lamm Gottes, unschuldig', 'Lamm Gottes (Agnus Dei)', 1),
('190.2', 'Christe, du Lamm Gottes', 'Lamm Gottes (Agnus Dei)', 1),
('190.3', 'Lamm Gottes', 'Lamm Gottes (Agnus Dei)', 1),
('190.4', 'Siehe, das ist Gottes Lamm', 'Lamm Gottes (Agnus Dei)', 1),
('191', 'Herr Gott, dich loben wir (Te Deum)', 'Te Deum', 1),
('192', 'Kyrie eleison (Litanei)', 'Litanei', 1),
('193', 'Erhalt uns, Herr, bei deinem Wort', 'Wort Gottes', 3),
('194', 'O Gott, du höchster Gnadenhort', 'Wort Gottes', 3),
('195', 'Allein auf Gottes Wort will ich', 'Wort Gottes', 3),
('196', 'Herr, für dein Wort sei hoch gepreist', 'Wort Gottes', 6),
('197', 'Herr, öffne mir die Herzenstür', 'Wort Gottes', 3),
('198', 'Herr, dein Wort, die edle Gabe', 'Wort Gottes', 2),
('199', 'Gott hat das erste Wort', 'Wort Gottes', 5),
('200', 'Ich bin getauft auf deinen Namen', 'Taufe und Konfirmation', 6),
('201', 'Gehet hin in alle Welt', 'Taufe und Konfirmation', 1),
('202', 'Christ, unser Herr, zum Jordan kam', 'Taufe und Konfirmation', 7),
('203', 'Ach lieber Herre Jesu Christ, der du ein Kindlein worden bist', 'Taufe und Konfirmation', 6),
('204', 'Herr Christ, dein bin ich eigen', 'Taufe und Konfirmation', 4),
('205', 'Gott Vater, höre unsre Bitt', 'Taufe und Konfirmation', 4),
('206', 'Liebster Jesu, wir sind hier, deinem Worte nachzuleben', 'Taufe und Konfirmation', 5),
('207', 'Nun schreib ins Buch des Lebens', 'Taufe und Konfirmation', 3),
('208', 'Gott Vater, du hast deinen Namen', 'Taufe und Konfirmation', 3),
('209', 'Ich möcht'', dass einer mit mir geht', 'Taufe und Konfirmation', 4),
('210', 'Du hast mich, Herr, zu dir gerufen', 'Taufe und Konfirmation', 5),
('211', 'Gott, der du alles Leben schufst', 'Taufe und Konfirmation', 5),
('212', 'Voller Freude über dieses Wunder', 'Taufe und Konfirmation', 6),
('213', 'Kommt her, ihr seid geladen', 'Abendmahl', 6),
('214', 'Gott sei gelobet und gebenedeiet', 'Abendmahl', 3),
('215', 'Jesus Christus, unser Heiland, der von uns den Gotteszorn wandt', 'Abendmahl', 8),
('216', 'Du hast uns Leib und Seel gespeist', 'Abendmahl', 1),
('217', 'Herr Jesu Christe, mein getreuer Hirte', 'Abendmahl', 4),
('218', 'Schmücke dich, o liebe Seele', 'Abendmahl', 6),
('219', 'Herr Jesu Christ, du höchstes Gut', 'Abendmahl', 219),
('220', 'Herr, du wollest uns bereiten', 'Abendmahl', 1),
('221', 'Das sollt ihr, Jesu Jünger, nie vergessen', 'Abendmahl', 3),
('222', 'Im Frieden dein, o Herre mein', 'Abendmahl', 3),
('223', 'Das Wort geht von dem Vater aus', 'Abendmahl', 6),
('224', 'Du hast zu deinem Abendmahl', 'Abendmahl', 3),
('225', 'Komm, sag es allen weiter', 'Abendmahl', 3),
('226', 'Seht, das Brot, das wir hier teilen', 'Abendmahl', 6),
('227', 'Dank sei dir, Vater, für das ewge Leben', 'Abendmahl', 6),
('228', 'Er ist das Brot, er ist der Wein', 'Abendmahl', 3),
('229', 'Kommt mit Gaben und Lobgesang', 'Abendmahl', 3),
('230', 'Schaffe in mir, Gott, ein reines Herze', 'Beichte', 1),
('231', 'Dies sind die heilgen zehn Gebot', 'Beichte', 12),
('232', 'Allein zu dir, Herr Jesu Christ', 'Beichte', 4),
('233', 'Ach Gott und Herr, wie groß und schwer', 'Beichte', 5),
('234', '»So wahr ich lebe«, spricht dein Gott', 'Beichte', 7),
('235', 'O Herr, nimm unsre Schuld', 'Beichte', 4),
('236', 'Ohren gabst du mir', 'Beichte', 6),
('237', 'Und suchst du meine Sünde', 'Beichte', 3),
('238', 'Herr, vor dein Antlitz treten zwei', 'Trauung', 3),
('239', 'Freuet euch im Herren allewege', 'Trauung', 5),
('240', 'Du hast uns, Herr, in dir verbunden', 'Trauung', 3),
('241', 'Wach auf, du Geist der ersten Zeugen', 'Sammlung und Sendung', 8),
('242', 'Herr, nun selbst den Wagen halt', 'Sammlung und Sendung', 3),
('243', 'Lob Gott getrost mit Singen', 'Sammlung und Sendung', 6),
('244', 'Wach auf, wach auf, ''s ist hohe Zeit', 'Sammlung und Sendung', 10),
('245', 'Preis, Lob und Dank sei Gott dem Herren', 'Sammlung und Sendung', 5),
('246', 'Ach bleib bei uns, Herr Jesu Christ', 'Sammlung und Sendung', 7),
('247', 'Herr, unser Gott, lass nicht zuschanden werden', 'Sammlung und Sendung', 4),
('248', 'Treuer Wächter Israel''', 'Sammlung und Sendung', 7),
('249', 'Verzage nicht, du Häuflein klein', 'Sammlung und Sendung', 5),
('250', 'Ich lobe dich von ganzer Seelen', 'Sammlung und Sendung', 5),
('251', 'Herz und Herz vereint zusammen', 'Sammlung und Sendung', 7),
('252', 'Jesu, der du bist alleine', 'Sammlung und Sendung', 9),
('253', 'Ich glaube, dass die Heiligen', 'Sammlung und Sendung', 5),
('254', 'Wir wolln uns gerne wagen', 'Sammlung und Sendung', 4),
('255', 'O dass doch bald dein Feuer brennte', 'Sammlung und Sendung', 9),
('256', 'Einer ist''s, an dem wir hangen', 'Sammlung und Sendung', 5),
('257', 'Der du in Todesnächten', 'Sammlung und Sendung', 4),
('258', 'Zieht in Frieden eure Pfade', 'Sammlung und Sendung', 1),
('259', 'Kommt her, des Königs Aufgebot', 'Sammlung und Sendung', 3),
('260', 'Gleichwie mich mein Vater gesandt hat', 'Sammlung und Sendung', 2),
('261', 'Herr, wohin sollen wir gehen', 'Sammlung und Sendung', 1),
('262', 'Sonne der Gerechtigkeit (ökumenische Fassung)', 'Ökumene', 7),
('263', 'Sonne der Gerechtigkeit', 'Ökumene', 7),
('264', 'Die Kirche steht gegründet', 'Ökumene', 3),
('265', 'Nun singe Lob,du Christenheit', 'Ökumene', 5),
('266', 'Der Tag, mein Gott, ist nun vergangen', 'Ökumene', 5),
('267', 'Herr, du hast darum gebetet', 'Ökumene', 5),
('268', 'Strahlen brechen viele aus einem Licht', 'Ökumene', 5),
('269', 'Christus ist König, jubelt laut', 'Ökumene', 5),
('270', 'Herr, unser Herrscher, wie herrlich bist du', 'Psalmen und Lobgesänge', 6),
('271', 'Wie herrlich gibst du, Herr, dich zu erkennen', 'Psalmen und Lobgesänge', 8),
('272', 'Ich lobe meinen Gott von ganzem Herzen', 'Psalmen und Lobgesänge', 1),
('273', 'Ach Gott, vom Himmel sieh darein', 'Psalmen und Lobgesänge', 6),
('274', 'Der Herr ist mein getreuer Hirt', 'Psalmen und Lobgesänge', 5),
('275', 'In dich hab ich gehoffet, Herr', 'Psalmen und Lobgesänge', 7),
('276', 'Ich will, solang ich lebe', 'Psalmen und Lobgesänge', 5),
('277', 'Herr, deine Güte reicht, so weit der Himmel ist', 'Psalmen und Lobgesänge', 5),
('278', 'Wie der Hirsch lechzt nach frischem Wasser', 'Psalmen und Lobgesänge', 9),
('279', 'Jauchzt, alle Lande, Gott zu Ehren', 'Psalmen und Lobgesänge', 8),
('280', 'Es wolle Gott uns gnädig sein', 'Psalmen und Lobgesänge', 3),
('281', 'Erhebet er sich, unser Gott', 'Psalmen und Lobgesänge', 5),
('282', 'Wie lieblich schön, Herr Zebaoth', 'Psalmen und Lobgesänge', 6),
('283', 'Herr, der du vormals hast dein Land', 'Psalmen und Lobgesänge', 7),
('284', 'Das ist köstlich, dir zu sagen Lob und Preis', 'Psalmen und Lobgesänge', 4),
('285', 'Das ist ein köstlich Ding', 'Psalmen und Lobgesänge', 3),
('286', 'Singt, singt dem Herren neue Lieder', 'Psalmen und Lobgesänge', 4),
('287', 'Singet dem Herrn ein neues Lied', 'Psalmen und Lobgesänge', 4),
('288', 'Nun jauchzt dem Herren, alle Welt', 'Psalmen und Lobgesänge', 7),
('289', 'Nun lob, mein Seel, den Herren', 'Psalmen und Lobgesänge', 5),
('290', 'Nun danket Gott, erhebt und preiset', 'Psalmen und Lobgesänge', 7),
('291', 'Ich will dir danken, Herr', 'Psalmen und Lobgesänge', 3),
('292', 'Das ist mir lieb, dass du mich hörst', 'Psalmen und Lobgesänge', 5),
('293', 'Lobt Gott den Herrn, ihr Heiden all', 'Psalmen und Lobgesänge', 2),
('294', 'Nun saget Dank und lobt den Herren', 'Psalmen und Lobgesänge', 4),
('295', 'Wohl denen, die da wandeln', 'Psalmen und Lobgesänge', 4),
('296', 'Ich heb mein Augen sehnlich auf', 'Psalmen und Lobgesänge', 8),
('297', 'Wo Gott der Herr nicht bei uns hält', 'Psalmen und Lobgesänge', 6),
('298', 'Wenn der Herr einst die Gefangnen', 'Psalmen und Lobgesänge', 3),
('299', 'Aus tiefer Not schrei ich zu dir', 'Psalmen und Lobgesänge', 5),
('300', 'Lobt Gott, den Herrn der Herrlichkeit', 'Psalmen und Lobgesänge', 3),
('301', 'Danket Gott, denn er ist gut', 'Psalmen und Lobgesänge', 12),
('302', 'Du meine Seele, singe', 'Psalmen und Lobgesänge', 8),
('303', 'Lobe den Herren, o meine Seele', 'Psalmen und Lobgesänge', 8),
('304', 'Lobet den Herren, denn er ist sehr freundlich', 'Psalmen und Lobgesänge', 6),
('305', 'Singt das Lied der Freude über Gott', 'Psalmen und Lobgesänge', 4),
('306', 'Singt das Lied der Freude', 'Psalmen und Lobgesänge', 4),
('307', 'Selig sind, die da geistlich arm sind', 'Psalmen und Lobgesänge', 8),
('308', 'Mein Seel, o Herr, muss loben dich', 'Psalmen und Lobgesänge', 11),
('309', 'Hoch hebt den Herrn mein Herz', 'Psalmen und Lobgesänge', 4),
('310', 'Meine Seele erhebt den Herren', 'Psalmen und Lobgesänge', 1),
('311', 'Abraham, Abraham, verlass dein Land', 'Biblische Erzähllieder', 3),
('312', 'Kam einst zum Ufer', 'Biblische Erzähllieder', 7),
('313', 'Jesus, der zu den Fischern lief', 'Biblische Erzähllieder', 3),
('314', 'Jesus zieht in Jerusalem ein', 'Biblische Erzähllieder', 6),
('315', 'Ich will zu meinem Vater gehn', 'Biblische Erzähllieder', 7),
('316', 'Lobe den Herren, den mächtigen König der Ehren', 'Loben und Danken', 5),
('317', 'Lobe den Herren, den mächtigen König der Ehren', 'Loben und Danken', 5),
('318', 'O gläubig Herz, gebenedei', 'Loben und Danken', 9),
('319', 'Die beste Zeit im Jahr ist mein', 'Loben und Danken', 4),
('320', 'Nun lasst uns Gott dem Herren', 'Loben und Danken', 8),
('321', 'Nun danket alle Gott', 'Loben und Danken', 3),
('322', 'Nun danket all und bringet Ehr', 'Loben und Danken', 9),
('323', 'Man lobt dich in der Stille', 'Loben und Danken', 3),
('324', 'Ich singe dir mit Herz und Mund', 'Loben und Danken', 18),
('325', 'Sollt ich meinem Gott nicht singen', 'Loben und Danken', 10),
('326', 'Sei Lob und Ehr dem höchsten Gut', 'Loben und Danken', 9),
('327', 'Wunderbarer König', 'Loben und Danken', 4),
('328', 'Dir, dir, o Höchster, will ich singen', 'Loben und Danken', 7),
('329', 'Bis hierher hat mich Gott gebracht', 'Loben und Danken', 3),
('330', 'O dass ich tausend Zungen hätte', 'Loben und Danken', 7),
('331', 'Großer Gott, wir loben dich', 'Loben und Danken', 11),
('332', 'Lobt froh den Herrn, ihr jugendlichen Chöre', 'Loben und Danken', 4),
('333', 'Danket dem Herrn! Wir danken dem Herrn', 'Loben und Danken', 6),
('334', 'Danke für diesen guten Morgen', 'Loben und Danken', 6),
('335', 'Ich will den Herrn loben allezeit', 'Loben und Danken', 1),
('336', 'Danket, danket dem Herrn', 'Loben und Danken', 1),
('337', 'Lobet und preiset, ihr Völker, den Herrn', 'Loben und Danken', 1),
('338', 'Alte mit den Jungen sollen loben', 'Loben und Danken', 1),
('339', 'Mein Herz ist bereit', 'Loben und Danken', 1),
('340', 'Ich will dem Herrn singen mein Leben lang', 'Loben und Danken', 1),
('341', 'Nun freut euch, lieben Christen g''mein', 'Rechtfertigung und Zuversicht', 10),
('342', 'Es ist das Heil uns kommen her', 'Rechtfertigung und Zuversicht', 9),
('343', 'Ich ruf zu dir, Herr Jesu Christ', 'Rechtfertigung und Zuversicht', 5),
('344', 'Vater unser im Himmelreich', 'Rechtfertigung und Zuversicht', 9),
('345', 'Auf meinen lieben Gott', 'Rechtfertigung und Zuversicht', 5),
('346', 'Such, wer da will, ein ander Ziel', 'Rechtfertigung und Zuversicht', 5),
('347', 'Ach bleib mit deiner Gnade', 'Rechtfertigung und Zuversicht', 6),
('348', 'Gott verspricht: Ich will dich segnen', 'Rechtfertigung und Zuversicht', 1),
('349', 'Ich freu mich in dem Herren', 'Rechtfertigung und Zuversicht', 4),
('350', 'Christi Blut und Gerechtigkeit', 'Rechtfertigung und Zuversicht', 5),
('351', 'Ist Gott für mich, so trete', 'Rechtfertigung und Zuversicht', 13),
('352', 'Alles ist an Gottes Segen', 'Rechtfertigung und Zuversicht', 6),
('353', 'Jesus nimmt die Sünder an', 'Rechtfertigung und Zuversicht', 8),
('354', 'Ich habe nun den Grund gefunden', 'Rechtfertigung und Zuversicht', 7),
('355', 'Mir ist Erbarmung widerfahren', 'Rechtfertigung und Zuversicht', 5),
('356', 'Es ist in keinem andern Heil', 'Rechtfertigung und Zuversicht', 2),
('357', 'Ich weiß, woran ich glaube', 'Rechtfertigung und Zuversicht', 5),
('358', 'Es kennt der Herr die Seinen', 'Rechtfertigung und Zuversicht', 6),
('359', 'In dem Herren freuet euch', 'Rechtfertigung und Zuversicht', 6),
('360', 'Die ganze Welt hast du uns überlassen', 'Rechtfertigung und Zuversicht', 6),
('361', 'Befiehl du deine Wege', 'Angst und Vertrauen', 12),
('362', 'Ein feste Burg ist unser Gott', 'Angst und Vertrauen', 4),
('363', 'Kommt her zu mir, spricht Gottes Sohn', 'Angst und Vertrauen', 7),
('364', 'Was mein Gott will, gescheh allzeit', 'Angst und Vertrauen', 4),
('365', 'Von Gott will ich nicht lassen', 'Angst und Vertrauen', 8),
('366', 'Wenn wir in höchsten Nöten sein', 'Angst und Vertrauen', 7),
('367', 'Herr, wie du willst, so schick''s mit mir', 'Angst und Vertrauen', 3),
('368', 'In allen meinen Taten', 'Angst und Vertrauen', 7),
('369', 'Wer nur den lieben Gott lässt walten', 'Angst und Vertrauen', 7),
('370', 'Warum sollt ich mich denn grämen', 'Angst und Vertrauen', 12),
('371', 'Gib dich zufrieden und sei stille', 'Angst und Vertrauen', 15),
('372', 'Was Gott tut, das ist wohlgetan', 'Angst und Vertrauen', 6),
('373', 'Jesu, hilf siegen, du Fürste des Lebens', 'Angst und Vertrauen', 6),
('374', 'Ich steh in meines Herren Hand', 'Angst und Vertrauen', 5),
('375', 'Dass Jesus siegt, bleibt ewig ausgemacht', 'Angst und Vertrauen', 4),
('376', 'So nimm denn meine Hände', 'Angst und Vertrauen', 3),
('377', 'Zieh an die Macht, du Arm des Herrn', 'Angst und Vertrauen', 4),
('378', 'Es mag sein, dass alles fällt', 'Angst und Vertrauen', 5),
('379', 'Gott wohnt in einem Lichte', 'Angst und Vertrauen', 5),
('380', 'Ja, ich will euch tragen', 'Angst und Vertrauen', 7),
('381', 'Gott, mein Gott, warum hast du mich verlassen', 'Angst und Vertrauen', 4),
('382', 'Ich steh vor dir mit leeren Händen, Herr', 'Angst und Vertrauen', 3),
('383', 'Herr, du hast mich angerührt', 'Angst und Vertrauen', 4),
('384', 'Lasset uns mit Jesus ziehen', 'Umkehr und Nachfolge', 4),
('385', 'Mir nach, spricht Christus, unser Held', 'Umkehr und Nachfolge', 6),
('386', 'Eins ist not! Ach Herr, dies Eine', 'Umkehr und Nachfolge', 10),
('387', 'Mache dich, mein Geist, bereit', 'Umkehr und Nachfolge', 6),
('388', 'O Durchbrecher aller Bande', 'Umkehr und Nachfolge', 7),
('389', 'Ein reines Herz, Herr, schaff in mir', 'Umkehr und Nachfolge', 5),
('390', 'Erneure mich, o ewigs Licht', 'Umkehr und Nachfolge', 3),
('391', 'Jesu, geh voran', 'Umkehr und Nachfolge', 4),
('392', 'Gott rufet noch. Sollt ich nicht endlich hören', 'Umkehr und Nachfolge', 8),
('393', 'Kommt, Kinder, lasst uns gehen', 'Umkehr und Nachfolge', 11),
('394', 'Nun aufwärts froh den Blick gewandt', 'Umkehr und Nachfolge', 5),
('395', 'Vertraut den neuen Wegen', 'Umkehr und Nachfolge', 3),
('396', 'Jesu, meine Freude', 'Geborgen in Gottes Liebe', 6),
('397', 'Herzlich lieb hab ich dich, o Herr', 'Geborgen in Gottes Liebe', 3),
('398', 'In dir ist Freude', 'Geborgen in Gottes Liebe', 2),
('399', 'O Lebensbrünnlein tief und groß', 'Geborgen in Gottes Liebe', 7),
('400', 'Ich will dich lieben, meine Stärke', 'Geborgen in Gottes Liebe', 7),
('401', 'Liebe, die du mich zum Bilde', 'Geborgen in Gottes Liebe', 7),
('402', 'Meinen Jesus lass ich nicht', 'Geborgen in Gottes Liebe', 6),
('403', 'Schönster Herr Jesu', 'Geborgen in Gottes Liebe', 5),
('404', 'Herr Jesu, Gnadensonne', 'Geborgen in Gottes Liebe', 8),
('405', 'Halt im Gedächtnis Jesus Christ', 'Geborgen in Gottes Liebe', 8),
('406', 'Bei dir, Jesu, will ich bleiben', 'Geborgen in Gottes Liebe', 6),
('407', 'Stern, auf den ich schaue', 'Geborgen in Gottes Liebe', 3),
('408', 'Meinem Gott gehört die Welt', 'Geborgen in Gottes Liebe', 6),
('409', 'Gott liebt diese Welt', 'Geborgen in Gottes Liebe', 8),
('410', 'Christus, das Licht der Welt', 'Geborgen in Gottes Liebe', 4),
('411', 'Gott, weil er groß ist', 'Geborgen in Gottes Liebe', 1),
('412', 'So jemand spricht: »Ich liebe Gott«', 'Nächsten- und Feindesliebe', 8),
('413', 'Ein wahrer Glaube Gotts Zorn stillt', 'Nächsten- und Feindesliebe', 8),
('414', 'Lass mich, o Herr, in allen Dingen', 'Nächsten- und Feindesliebe', 4),
('415', 'Liebe, du ans Kreuz für uns erhöhte', 'Nächsten- und Feindesliebe', 4),
('416', 'O Herr, mach mich zu einem Werkzeug deines Friedens', 'Nächsten- und Feindesliebe', 1),
('417', 'Lass die Wurzel unsers Handelns Liebe sein', 'Nächsten- und Feindesliebe', 2),
('418', 'Brich dem Hungrigen dein Brot', 'Nächsten- und Feindesliebe', 5),
('419', 'Hilf, Herr meines Lebens', 'Nächsten- und Feindesliebe', 5),
('420', 'Brich mit den Hungrigen dein Brot', 'Nächsten- und Feindesliebe', 5),
('421', 'Verleih uns Frieden gnädiglich', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 1),
('422', 'Du Friedefürst, Herr Jesu Christ', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 3),
('423', 'Herr, höre, Herr, erhöre', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 11),
('424', 'Deine Hände, großer Gott', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 3),
('425', 'Gib uns Frieden jeden Tag', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 3),
('426', 'Es wird sein in den letzten Tagen', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 3),
('427', 'Solang es Menschen gibt auf Erden', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 5),
('428', 'Komm in unsre stolze Welt', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 5),
('429', 'Lobt und preist die herrlichen Taten des Herrn', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 3),
('430', 'Gib Frieden, Herr, gib Frieden', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 4),
('431', 'Gott, unser Ursprung, Herr des Raums', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 3),
('432', 'Gott gab uns Atem, damit wir leben', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 3),
('433', 'Hevenu schalom alejchem - Wir wünschen Frieden euch allen', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 2),
('434', 'Schalom chaverim - Der Friede des Herrn geleite euch', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 1),
('435', 'Dona nobis pacem', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 1),
('436', 'Herr, gib uns deinen Frieden', 'Erhaltung der Schöpfung, Frieden und Gerechtigkeit', 1),
('437', 'Die helle Sonn leucht'' jetzt herfür', 'Morgen', 4),
('438', 'Der Tag bricht an und zeiget sich', 'Morgen', 6),
('439', 'Es geht daher des Tages Schein', 'Morgen', 6),
('440', 'All Morgen ist ganz frisch und neu', 'Morgen', 4),
('441', 'Du höchstes Licht, du ewger Schein', 'Morgen', 8),
('442', 'Steht auf, ihr lieben Kinderlein', 'Morgen', 9),
('443', 'Aus meines Herzens Grunde', 'Morgen', 7),
('444', 'Die güldene Sonne', 'Morgen', 5),
('445', 'Gott des Himmels und der Erden', 'Morgen', 7),
('446', 'Wach auf, mein Herz, und singe', 'Morgen', 9),
('447', 'Lobet den Herren alle, die ihn ehren', 'Morgen', 10),
('448', 'Lobet den Herren alle, die ihn ehren', 'Morgen', 10),
('449', 'Die güldne Sonne', 'Morgen', 12),
('450', 'Morgenglanz der Ewigkeit', 'Morgen', 5),
('451', 'Mein erst Gefühl sei Preis und Dank', 'Morgen', 10),
('452', 'Er weckt mich alle Morgen', 'Morgen', 5),
('453', 'Schon bricht des Tages Glanz hervor', 'Morgen', 5),
('454', 'Auf und macht die Herzen weit', 'Morgen', 6),
('455', 'Morgenlicht leuchtet, rein wie am Anfang', 'Morgen', 3),
('456', 'Vom Aufgang der Sonne', 'Morgen', 1),
('457', 'Der Tag ist seiner Höhe nah', 'Mittag und das tägliche Brot', 12),
('458', 'Wir danken Gott für seine Gaben', 'Mittag und das tägliche Brot', 1),
('459', 'Die Sonn hoch an dem Himmel steht', 'Mittag und das tägliche Brot', 3),
('460', 'Lobet den Herrn und dankt ihm seine Gaben', 'Mittag und das tägliche Brot', 1),
('461', 'Aller Augen warten auf dich, Herre', 'Mittag und das tägliche Brot', 1),
('462', 'Wir danken dir, Herr Jesu Christ, dass du unser Gast gewesen bist', 'Mittag und das tägliche Brot', 1),
('463', 'Alle guten Gaben, alles, was wir haben', 'Mittag und das tägliche Brot', 1),
('464', 'Herr, gib uns unser täglich Brot', 'Mittag und das tägliche Brot', 2),
('465', 'Komm, Herr Jesu, sei du unser Gast', 'Mittag und das tägliche Brot', 1),
('466', 'Segne, Herr, was deine Hand', 'Mittag und das tägliche Brot', 1),
('467', 'Hinunter ist der Sonne Schein', 'Abend', 4),
('468', 'Ach lieber Herre Jesu Christ, weil du ein Kind gewesen bist', 'Abend', 4),
('469', 'Christe, du bist der helle Tag', 'Abend', 7),
('470', 'Der du bist drei in Einigkeit', 'Abend', 3),
('471', 'Die Nacht ist kommen', 'Abend', 5),
('472', 'Der Tag hat sich geneiget', 'Abend', 6),
('473', 'Mein schönste Zier und Kleinod bist', 'Abend', 4),
('474', 'Mit meinem Gott geh ich zur Ruh', 'Abend', 3),
('475', 'Werde munter, mein Gemüte', 'Abend', 8),
('476', 'Die Sonn hat sich mit ihrem Glanz gewendet', 'Abend', 7),
('477', 'Nun ruhen alle Wälder', 'Abend', 9),
('478', 'Nun sich der Tag geendet hat', 'Abend', 9),
('479', 'Der lieben Sonne Licht und Pracht', 'Abend', 4),
('480', 'Nun schläfet man', 'Abend', 3),
('481', 'Nun sich der Tag geendet, mein Herz sich zu die wendet', 'Abend', 5),
('482', 'Der Mond ist aufgegangen', 'Abend', 7),
('483', 'Herr, bleibe bei uns', 'Abend', 1),
('484', 'Müde bin ich, geh zur Ruh', 'Abend', 4),
('485', 'Du Schöpfer aller Wesen', 'Abend', 6),
('486', 'Ich liege, Herr, in deiner Hut', 'Abend', 11),
('487', 'Abend ward, bald kommt die Nacht', 'Abend', 4),
('488', 'Bleib bei mir, Herr! Der Abend bricht herein', 'Abend', 5),
('489', 'Gehe ein in deinen Frieden', 'Abend', 2),
('490', 'Der Tag ist um, die Nacht kehrt wieder', 'Abend', 4),
('491', 'Bevor die Sonne sinkt', 'Abend', 4),
('492', 'Ruhet von des Tages Müh', 'Abend', 1),
('493', 'Eine ruhige Nacht', 'Abend', 1),
('494', 'In Gottes Namen fang ich an', 'Arbeit', 6),
('495', 'O Gott, du frommer Gott', 'Arbeit', 8),
('496', 'Lass dich, Herr Jesu Christ, durch mein Gebet bewegen', 'Arbeit', 1),
('497', 'Ich weiß, mein Gott, dass all mein Tun', 'Arbeit', 14),
('498', 'In Gottes Namen fahren wir', 'Auf Reisen', 4),
('499', 'Erd und Himmel sollen singen', 'Natur und Jahreszeiten', 3),
('500', 'Lobt Gott in allen Landen', 'Natur und Jahreszeiten', 4),
('501', 'Wie lieblich ist der Maien', 'Natur und Jahreszeiten', 4),
('502', 'Nun preiset alle Gottes Barmherzigkeit', 'Natur und Jahreszeiten', 5),
('503', 'Geh aus, mein Herz, und suche Freud', 'Natur und Jahreszeiten', 15),
('504', 'Himmel, Erde, Luft und Meer', 'Natur und Jahreszeiten', 6),
('505', 'Die Ernt ist nun zu Ende', 'Natur und Jahreszeiten', 7),
('506', 'Wenn ich, o Schöpfer, deine Macht', 'Natur und Jahreszeiten', 6),
('507', 'Himmels Au, licht und blau', 'Natur und Jahreszeiten', 7),
('508', 'Wir pflügen, und wir streuen', 'Natur und Jahreszeiten', 4),
('509', 'Kein Tierlein ist auf Erden', 'Natur und Jahreszeiten', 5),
('510', 'Freuet euch der schönen Erde', 'Natur und Jahreszeiten', 5),
('511', 'Weißt du, wieviel Sternlein stehen', 'Natur und Jahreszeiten', 3),
('512', 'Herr, die Erde ist gesegnet', 'Natur und Jahreszeiten', 6),
('513', 'Das Feld ist weiß', 'Natur und Jahreszeiten', 7),
('514', 'Gottes Geschöpfe, kommt zuhauf', 'Natur und Jahreszeiten', 7),
('515', 'Laudato si - Sei gepriesen', 'Natur und Jahreszeiten', 9),
('516', 'Christus, der ist mein Leben', 'Sterben und ewiges Leben, Bestattung', 7),
('517', 'Ich wollt, dass ich daheime wär', 'Sterben und ewiges Leben, Bestattung', 12),
('518', 'Mitten wir im Leben sind', 'Sterben und ewiges Leben, Bestattung', 3),
('519', 'Mit Fried und Freud ich fahr dahin', 'Sterben und ewiges Leben, Bestattung', 4),
('520', 'Nun legen wir den Leib ins Grab', 'Sterben und ewiges Leben, Bestattung', 7),
('521', 'O Welt, ich muss dich lassen', 'Sterben und ewiges Leben, Bestattung', 3),
('522', 'Wenn mein Stündlein vorhanden ist', 'Sterben und ewiges Leben, Bestattung', 5),
('523', 'Valet will ich dir geben', 'Sterben und ewiges Leben, Bestattung', 5),
('524', 'Freu dich sehr, o meine Seele', 'Sterben und ewiges Leben, Bestattung', 8),
('525', 'Mach''s mit mir, Gott, nach deiner Güt', 'Sterben und ewiges Leben, Bestattung', 5),
('526', 'Jesus, meine Zuversicht', 'Sterben und ewiges Leben, Bestattung', 7),
('527', 'Die Herrlichkeit der Erden', 'Sterben und ewiges Leben, Bestattung', 10),
('528', 'Ach wie flüchtig, ach wie nichtig', 'Sterben und ewiges Leben, Bestattung', 8),
('529', 'Ich bin ein Gast auf Erden', 'Sterben und ewiges Leben, Bestattung', 12),
('530', 'Wer weiß, wie nahe mir mein Ende', 'Sterben und ewiges Leben, Bestattung', 8),
('531', 'Noch kann ich es nicht fassen', 'Sterben und ewiges Leben, Bestattung', 3),
('532', 'Nun sich das Herz von allem löste', 'Sterben und ewiges Leben, Bestattung', 3),
('533', 'Du kannst nicht tiefer fallen', 'Sterben und ewiges Leben, Bestattung', 3),
('534', 'Herr, lehre uns, dass wir sterben müssen', 'Sterben und ewiges Leben, Bestattung', 2),
('535', 'Gloria sei dir gesungen', 'Sterben und ewiges Leben, Bestattung', 1),
('536', 'Leitlied des nordelbischen Liederteils: Gott ist mein Lied', 'Gott ist mein Lied', 0),
('537', 'Die Nacht ist hin, der Tag bricht an', 'Zum Beginn des Kirchenjahrs', 0),
('538', 'Auf, auf, ihr Christen alle', 'Advent', 0),
('539', 'Tragt in die Welt nun ein Licht', 'Advent', 0),
('540', 'Christum wir sollen loben schon', 'Weihnachten', 0),
('541', 'Der Tag, der ist so freudenreich', 'Weihnachten', 0),
('542', 'Freut euch ihr lieben Christen', 'Weihnachten', 0),
('543', 'Als ich bei meinen Schafen wacht', 'Weihnachten', 0),
('544', 'Wir singen dir, Immanuel', 'Weihnachten', 0),
('545', 'Christus ist geboren', 'Weihnachten', 0),
('546', 'Helft mir Gotts Güte preisen', 'Jahreswende', 0),
('547', 'Was fürchtst du, Feind Herodes, sehr', 'Passion', 0),
('548', 'Da Jesus an dem Kreuze stund', 'Passion', 0),
('549', 'Der du, Herr Jesu, ruh und Rast', 'Passion', 0),
('550', 'Kommt, ihr Menschen, nehmt zu Herzen', 'Passion', 0),
('551', 'Nun ist der Himmel aufgetan', 'Ostern', 0),
('552', 'Jesus unser Trost und Leben', 'Ostern', 0),
('553', 'Wie morgenrot der Tag erwacht', 'Ostern', 0),
('554', 'Nun freut euch, Gottes Kinder all', 'Himmelfahrt', 0),
('555', 'Komm, Heiliger Geist, der Leben schafft', 'Pfingsten', 0),
('556', 'Sagt, wer kann den Wind sehn?', 'Pfingsten', 0),
('557', 'Herr Gott, dich loben alle wir', 'Michaelistag, 29. September', 0),
('558', 'Amen, Gott Vater und Sohne', 'Eingang und Ausgang', 0),
('559', 'O Adoramus te, Domine', 'Eingang und Ausgang', 0),
('560', 'Wach auf, meins Herzens Schöne', 'Wort Gottes', 0),
('561', 'Walte, walte nah und fern', 'Wort Gottes', 0),
('562', 'Gott, mien König, maak mi still', 'Wort Gottes', 0),
('563', 'Ach leewe Herre Jesus Christ', 'Taufe und Konfirmation', 0),
('564', 'Wir bringen, Gott (Herr), dies Kind zu dir', 'Taufe und Konfirmation', 0),
('565', 'Segne dieses Kind und hilf uns, ihm zu helfen', 'Taufe und Konfirmation', 0),
('566', 'Kind du bist uns anvertraut', 'Taufe und Konfirmation', 0),
('567', 'Du öffnest, Herr, die Türen', 'Taufe und Konfirmation', 0),
('568', 'Wasser vom Himmel', 'Taufe und Konfirmation', 0),
('569', 'Du hast uns, Herr, gerufen', 'Taufe und Konfirmation', 6),
('570', 'Herr Godt, nun sy gepryset', 'Abendmahl', 0),
('571', 'O Jesu, dir sei ewig Dank', 'Abendmahl', 0),
('572', 'Wie der Herr vor Zeiten mit den Jüngern saß', 'Abendmahl', 0),
('573', 'Die Stunde ist da, Jesus Christus', 'Abendmahl', 0),
('574', 'Sprick sülm, Herr, uns to samen', 'Trauung', 0),
('575', 'Herr, lass uns füreinander leben', 'Trauung', 0),
('576', 'Ewig steht fest der Kirche Haus', 'Sammlung und Sendung', 0),
('577', 'Lass uns in deinem Namen, Herr', 'Sammlung und Sendung', 0),
('578', 'Der Herr ist mein Hirte', 'Psalmen und Lobgesänge', 0),
('579', 'Der Herr ist mein Hirte', 'Psalmen und Lobgesänge', 0),
('580', 'Ich will Gott loben allezeit', 'Psalmen und Lobgesänge', 0),
('581', 'Ja, ich will singen', 'Psalmen und Lobgesänge', 0),
('582', 'Cantai ao Senhor: Singt Gott, unserm Herrn', 'Psalmen und Lobgesänge', 0),
('583', 'Jubilate Deo:Jauchze Erd und Himmel', 'Psalmen und Lobgesänge', 0),
('584', 'Hineh ma tow uma naim: Schön ist''s, wenn Brüder und Schwestern', 'Psalmen und Lobgesänge', 0),
('585', 'Dankt dem Herrn, denn er ist freundlich', 'Psalmen und Lobgesänge', 0),
('586', 'Gottes Lob wandert, und Erde darf hören', 'Psalmen und Lobgesänge', 0),
('587', 'Gott, den Vater, ewig preist', 'Loben und Danken', 0),
('588', 'Gott ist König, sein ist alle Macht über diese Welt', 'Loben und Danken', 0),
('589', 'Ich freue mich und springe', 'Loben und Danken', 0),
('590', 'Vater unser im Himmel', 'Loben und Danken', 0),
('591', 'Asante sana Yesu: Wir danken dir, Herr Jesu', 'Loben und Danken', 0),
('592', 'Lieber Gott, ich danke dir', 'Loben und Danken', 0),
('593', 'Durch Adams Fall ist ganz verderbt', 'Rechtfertigung und Zuversicht', 0),
('594', 'Der Glaub ist ein lebendig Kraft', 'Rechtfertigung und Zuversicht', 0),
('595', 'Vor deinem Thron tret ich hiermit', 'Rechtfertigung und Zuversicht', 0),
('596', 'Herr, durch den Glauben wohn in mir', 'Rechtfertigung und Zuversicht', 0),
('597', 'Lebenssonne, deren Strahlen', 'Rechtfertigung und Zuversicht', 0),
('598', 'Herr, giff mi Kraft to''n Beden', 'Rechtfertigung und Zuversicht', 0),
('599', 'Wi hebbt en König, Lüüd höört to', 'Rechtfertigung und Zuversicht', 0),
('600', 'Wir strecken unsre Hände aus wie leere Schalen', 'Rechtfertigung und Zuversicht', 0),
('601', 'Hilf uns, Herr, in allen Dingen', 'Angst und Vertrauen', 0),
('602', 'Harre, meine Seele, harre des Herrn', 'Angst und Vertrauen', 0),
('603', 'Weiß ich den Weg auch nicht', 'Angst und Vertrauen', 0),
('604', 'Mit Gott will ik mien''n Weg nu gahn', 'Angst und Vertrauen', 0),
('605', 'Gott is bi di. Wees man nich bang', 'Angst und Vertrauen', 0),
('606', 'Freunde, dass der Mandelzweig', 'Angst und Vertrauen', 4),
('607', 'Fürchte dich nicht, gefangen in deiner Angst', 'Angst und Vertrauen', 0),
('608', 'Wenn wir in Wassersnöten sein', 'Bei Sturm und in Wassernöten', 0),
('609', 'Wie mit grimmgem Unverstand', 'Bei Sturm und in Wassernöten', 0),
('610', 'Wir dienen, Herr, um keinen Lohn', 'Umkehr und Nachfolge', 0),
('611', 'Wohin denn sollen wir gehen', 'Umkehr und Nachfolge', 0),
('612', 'Ein Schiff, dass sich Gemeinde nennt', 'Umkehr und Nachfolge', 0),
('613', 'Selig seid ihr, wenn ihr einfach lebt', 'Umkehr und Nachfolge', 0),
('614', 'Schweige und höre', 'Umkehr und Nachfolge', 0),
('615', 'Ich bete an die Macht der Liebe', 'Geborgen in Gottes Liebe', 0),
('616', 'Wer kann der Treu vergessen', 'Geborgen in Gottes Liebe', 0),
('617', 'Du hest hendal di laten to mi', 'Geborgen in Gottes Liebe', 0),
('618', 'Einer muss wachen in langer Nacht', 'Geborgen in Gottes Liebe', 0),
('619', 'Herr, von dir kommt alles Leben', 'Geborgen in Gottes Liebe', 0),
('620', 'Ins Wasser fällt ein Stein', 'Geborgen in Gottes Liebe', 3),
('621', 'Kumbaya, my Lord: Komm zu mir, mein Gott', 'Geborgen in Gottes Liebe', 0),
('622', 'Weit wie das Meer ist Gottes große Liebe', 'Geborgen in Gottes Liebe', 0),
('623', 'Herr, deine Liebe ist wie Gras und Ufer', 'Geborgen in Gottes Liebe', 4),
('624', 'Ubi caritas et amor: Wo die Liebe wohnt und Güte', 'Geborgen in Gottes Liebe', 0),
('625', 'Da pacem, Domine', 'Frieden und Gerechtigkeit', 0),
('626', 'O heilige Dreifaltigkeit', 'Morgen', 0),
('627', 'Wi seggt di Dank vun Hartensgrunn', 'Morgen', 0),
('628', 'Gelobt sei deine Treu', 'Morgen', 4),
('629', 'Sieh, da hebt die Sonne sich übers Meer', 'Morgen', 0),
('630', 'Herr Gott, gib uns das täglich Brot', 'Mittag und das tägliche Brot', 0),
('631', 'Wir sitzen an gedeckten Tischen', 'Mittag und das tägliche Brot', 0),
('632', 'Glädjens Herre, varen gäst: Herr der Freude, Herr der Welt', 'Mittag und das tägliche Brot', 0),
('633', 'Christe, der du bist Tag und Licht', 'Abend', 0),
('634', 'Walts Gott, mein Werk ich lasse', 'Abend', 0),
('635', 'Nun wollen wir singen das Abendlied', 'Abend', 0),
('636', 'Des Tages Glanz erloschen ist', 'Abend', 0),
('637', 'Der Lärm verebbt, und die Last wird leichter', 'Abend', 0),
('638', 'So ist die Woche nun geschlossen', 'Wochenschluss', 0),
('639', 'Nun steht in Laub und Blüte', 'Natur und Jahreszeiten', 0),
('640', 'Ich weiß ein lieblich Engelspiel', 'Sterben und ewiges Leben, Bestattung', 0),
('641', 'Herlich tut mich verlangen', 'Sterben und ewiges Leben, Bestattung', 0),
('642', 'Alle Menschen müssen sterben', 'Sterben und ewiges Leben, Bestattung', 0),
('643', 'Im Himmelreich, im Himmelreich', 'Sterben und ewiges Leben, Bestattung', 0),
('644.1', 'Ehre sei dem Vater', 'Liturgische Gesänge', 1),
('644.2', 'Gloria Patri', 'Liturgische Gesänge', 1),
('645', 'Ehr sei dem Vater', 'Liturgische Gesänge', 0),
('646', 'Ehr sei dem Vater', 'Liturgische Gesänge', 0),
('647', 'Ehr sei Gott Vater', 'Liturgische Gesänge', 0),
('648', 'Lob, Ehr und Preis in süßem Ton', 'Liturgische Gesänge', 0),
('649', 'Lob sei in''s Himmels Throne', 'Liturgische Gesänge', 0),
('650', 'Gott Vater sei Lob, Ehr und Preis', 'Liturgische Gesänge', 0),
('651', 'Dir, ewger Vater droben', 'Liturgische Gesänge', 0),
('652', 'Ehr sei im Himmel droben', 'Liturgische Gesänge', 0),
('653', 'Gott wir wollen ehren', 'Liturgische Gesänge', 0),
('654', 'Lob, Ehr und Preis sei Gott bereit''', 'Liturgische Gesänge', 0),
('655', 'Lob, Ehr sei Gott im höchsten Throne', 'Liturgische Gesänge', 0),
('656', 'Lob, Ehr sei Gott im höchsten Throne', 'Liturgische Gesänge', 0),
('657', 'Singel all mit hellem Tone', 'Liturgische Gesänge', 0),
('658', 'Dir, Herr, sei Lob und Ehre heut und morgen', 'Liturgische Gesänge', 0),
('659', 'Dir, Vater, der du ewig bist', 'Liturgische Gesänge', 0),
('660', 'Gott, dir sei Preis und Ehre', 'Liturgische Gesänge', 0),
('661', 'Dir, Gott Vater droben', 'Liturgische Gesänge', 0),
('662', 'Vater und Sohne', 'Liturgische Gesänge', 0),
('663', 'Gott Vater, der du ewig bist', 'Liturgische Gesänge', 0),
('664', 'Dir, Hirt und Hüter', 'Liturgische Gesänge', 0),
('665', 'Preis, Ehr sei Gott im allerhöchsten Thron', 'Liturgische Gesänge', 0),
('666.1', 'Kyrie eleison', 'Liturgische Gesänge', 1),
('666.2', 'Kyrie eleison', 'Liturgische Gesänge', 1),
('666.3', 'Kyrie eleison', 'Liturgische Gesänge', 1),
('667.1', 'Ehre sei Gott in der Höhe', 'Liturgische Gesänge', 1),
('667.2', 'Dir Gott im Himmel Preis und Ehr', 'Liturgische Gesänge', 1),
('668.1', 'Halleluja', 'Liturgische Gesänge', 1),
('668.2', 'Halleluja', 'Liturgische Gesänge', 1),
('668.3', 'Alleluja', 'Liturgische Gesänge', 1),
('669.1', 'Ehre sei dir, Herre', 'Liturgische Gesänge', 1),
('669.2', 'Ehre sei dir, Herr', 'Liturgische Gesänge', 1),
('670.1', 'Ich glaube an Gott, den Vater, den Allmächtigen', 'Liturgische Gesänge', 1),
('670.2', 'Wir glauben an den einen Gott', 'Liturgische Gesänge', 1),
('670.3', 'Wir glauben an Gott Vater', 'Liturgische Gesänge', 1),
('671', 'Der Herr sei mit euch', 'Liturgische Gesänge', 0),
('672.1', 'Heilig ist Gott der Vater', 'Liturgische Gesänge', 1),
('672.2', 'Heilig, heilig, heilig ist Gott der Herr Zebaoth', 'Liturgische Gesänge', 1),
('672.3', 'Heilig, heilig, heilig Gott, Herr aller Mächte und Gewalten', 'Liturgische Gesänge', 1),
('672.4', 'Sanctus, sanctus sanctus Dominus: Heilig, heilig, heilig ist der Herr', 'Liturgische Gesänge', 1),
('672.5', 'Hosanna', 'Liturgische Gesänge', 1),
('673.1', 'Vater unser im Himmel', 'Liturgische Gesänge', 1),
('673.2', 'Vater unser im Himnmel', 'Liturgische Gesänge', 1),
('674.1', 'Der Friede des Herren sei mit euch allen', 'Liturgische Gesänge', 1),
('674.2', 'Der Friede des Herrn sei mit euch allezeit', 'Liturgische Gesänge', 1),
('675.1', 'Lamm Gottes', 'Liturgische Gesänge', 1),
('675.2', 'O du Gotteslamm', 'Liturgische Gesänge', 1),
('675.3', 'Siehe, das ist Gottes Lamm', 'Liturgische Gesänge', 1),
('676.1', 'Danket dem Herrn', 'Liturgische Gesänge', 1),
('676.2', 'Danket dem Herrn', 'Liturgische Gesänge', 1),
('677.1', 'Gehet hin im Frieden des Herrn', 'Liturgische Gesänge', 1),
('677.2', 'Gehet hin im Frieden des Herrn', 'Liturgische Gesänge', 1),
('677.3', 'Gehet hin im Frieden des Herrn', 'Liturgische Gesänge', 1),
('677.4', 'Gehet hin im Frieden', 'Liturgische Gesänge', 1),
('702', 'Psalm 1', 'Psalmen in Auswahl', 0),
('703', 'Psalm 4', 'Psalmen in Auswahl', 0),
('704', 'Psalm 6', 'Psalmen in Auswahl', 0),
('705', 'Psalm 8', 'Psalmen in Auswahl', 0),
('706', 'Psalm 13', 'Psalmen in Auswahl', 0),
('707', 'Psalm 18', 'Psalmen in Auswahl', 0),
('708', 'Psalm 19', 'Psalmen in Auswahl', 0),
('709', 'Psalm 22 I', 'Psalmen in Auswahl', 0),
('710', 'Psalm 22 II', 'Psalmen in Auswahl', 0),
('711', 'Psalm 23', 'Psalmen in Auswahl', 0),
('712', 'Psalm 24', 'Psalmen in Auswahl', 0),
('713', 'Psalm 25', 'Psalmen in Auswahl', 0),
('714', 'Psalm 27', 'Psalmen in Auswahl', 0),
('715', 'Psalm 30', 'Psalmen in Auswahl', 0),
('716', 'Psalm 31', 'Psalmen in Auswahl', 0),
('717', 'Psalm 32', 'Psalmen in Auswahl', 0),
('718', 'Psalm 34', 'Psalmen in Auswahl', 0),
('719', 'Psalm 36', 'Psalmen in Auswahl', 0),
('720', 'Psalm 37', 'Psalmen in Auswahl', 0),
('721', 'Psalm 38', 'Psalmen in Auswahl', 0),
('722', 'Psalm 39', 'Psalmen in Auswahl', 0),
('723', 'Psalm 42', 'Psalmen in Auswahl', 0),
('724', 'Psalm 43', 'Psalmen in Auswahl', 0),
('725', 'Psalm 46', 'Psalmen in Auswahl', 0),
('726', 'Psalm 47', 'Psalmen in Auswahl', 0),
('727', 'Psalm 51', 'Psalmen in Auswahl', 0),
('728', 'Psalm 57', 'Psalmen in Auswahl', 0),
('729', 'Psalm 63', 'Psalmen in Auswahl', 0),
('730', 'Psalm 67', 'Psalmen in Auswahl', 0),
('731', 'Psalm 69', 'Psalmen in Auswahl', 0),
('732', 'Psalm 71', 'Psalmen in Auswahl', 0),
('733', 'Psalm 73', 'Psalmen in Auswahl', 0),
('734', 'Psalm 84', 'Psalmen in Auswahl', 0),
('735', 'Psalm 90', 'Psalmen in Auswahl', 0),
('736', 'Psalm 91', 'Psalmen in Auswahl', 0),
('737', 'Psalm 92', 'Psalmen in Auswahl', 0),
('738', 'Psalm 96', 'Psalmen in Auswahl', 0),
('739', 'Psalm 98', 'Psalmen in Auswahl', 0),
('740', 'Psalm 100', 'Psalmen in Auswahl', 0),
('741', 'Psalm 102', 'Psalmen in Auswahl', 0),
('742', 'Psalm 103', 'Psalmen in Auswahl', 0),
('743', 'Psalm 104', 'Psalmen in Auswahl', 0),
('744', 'Psalm 111', 'Psalmen in Auswahl', 0),
('745', 'Psalm 113', 'Psalmen in Auswahl', 0),
('746', 'Psalm 116', 'Psalmen in Auswahl', 0),
('747', 'Psalm 118', 'Psalmen in Auswahl', 0),
('748', 'Psalm 119', 'Psalmen in Auswahl', 0),
('749', 'Psalm 121', 'Psalmen in Auswahl', 0),
('750', 'Psalm 126', 'Psalmen in Auswahl', 0),
('751', 'Psalm 130', 'Psalmen in Auswahl', 0),
('752', 'Psalm 134', 'Psalmen in Auswahl', 0),
('753', 'Psalm 136', 'Psalmen in Auswahl', 0),
('754', 'Psalm 139', 'Psalmen in Auswahl', 0),
('755', 'Psalm 143', 'Psalmen in Auswahl', 0),
('756', 'Psalm 145', 'Psalmen in Auswahl', 0),
('757', 'Psalm 146', 'Psalmen in Auswahl', 0),
('758', 'Psalm 150', 'Psalmen in Auswahl', 0),
('759', 'Matthäus 5', 'Psalmen in Auswahl', 0),
('760', 'Philipper 2', 'Psalmen in Auswahl', 0),
('789.1', 'Laudate omnes gentes', 'Taizé', 1),
('789.2', 'Bleibet hier und wachet mit mir!', 'Taizé', 1),
('789.3', 'Freuet euch im Herrn', 'Taizé', 1),
('789.4', 'Halleluja', 'Taizé', 1),
('789.5', 'Oculi nostri ad Dominum Deum', 'Taizé', 1),
('789.6', 'Kyrie, Kyrie eleison', 'Taizé', 1),
('789.7', 'Bleib mit deiner Gnade bei uns', 'Taizé', 1)